#pragma once
enum ElementType{LINE,RECTANGLE,CIRCLE,CURVE};

const COLORREF BLACK=RGB(0,0,0);
const COLORREF RED=RGB(255,0,0);
const COLORREF GREEN=RGB(0,255,0);
const COLORREF BLUE=RGB(0,0,255);